# Generated by Django 3.1 on 2020-08-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200816_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='myurlsh',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
