# Generated by Django 3.1 on 2020-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_myurlsh_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurlsh',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
